[general]
Blacklist = [
  "minecraft:shulker",
  "minecraft:armor_stand",
  "minecraft:squid",
  "minecraft:cod",
  "minecraft:salmon",
  "minecraft:pufferfish",
  "minecraft:tropical_fish",
  "dummmmmmy:target_dummy",
  "aquaculture:perch",
  "aquaculture:minnow",
  "aquaculture:bluegill",
  "aquaculture:gar",
  "aquaculture:atlantic_cod",
  "aquaculture:blackfish",
  "aquaculture:pacific_halibut",
  "aquaculture:atlantic_halibut",
  "aquaculture:atlantic_herring",
  "aquaculture:pink_salmon",
  "aquaculture:pollock",
  "aquaculture:rainbow_trout",
  "aquaculture:bayad",
  "aquaculture:boulti",
  "aquaculture:capitaine",
  "aquaculture:synodontis",
  "aquaculture:smallmouth",
  "aquaculture:brown_trout",
  "aquaculture:carp",
  "aquaculture:catfish",
  "aquaculture:muskellunge",
  "aquaculture:arapaima",
  "aquaculture:piranha",
  "aquaculture:tambaqui",
  "aquaculture:brown_shrooma",
  "aquaculture:red_shrooma",
  "aquaculture:jellyfish",
  "aquaculture:red_grouper",
  "aquaculture:tuna",
  "upgrade_aquatic:glow_squid",
  "upgrade_aquatic:nautilus",
  "upgrade_aquatic:pike",
  "upgrade_aquatic:lionfish",
  "upgrade_aquatic:perch",
  "artifacts:mimic",
]
